### ISSUE TITLE
Tezos Public Baking

### ISSUE THREAD

**Issue by John-P-Hopkins** [tez-capital/docs.tez.capital_content#1]
The contact information for TzStats is outdated, the current contact information is: tzstats@trili.tech

The contact information for Ledger leads to a 404 error. I was unable to find a way to contact them to list a new baker.

**Comment by Primate411** [comment]
Thank you for reporting. I updated the Trilitech info and removed the Ledger contact. They no longer accept new Tezos bakers afaik.
